### ISSUE TITLE
Step 3 Summary

### ISSUE THREAD

**Issue by dallincrane** [DevMountain/DevMtn-Node-Introduction#7]
The step 3 summary says "In this step we will create the basic outline of our server in a javascript file". I understand this, but the most important thing a student learns at DevMountain is how to ask the questions they have. Let's use language that matches our environment, and define those words if we need to. The step 3 summary might be better written like the following:

In this step we will create the file where Node starts to read our Javascript code. This file is also called the "entry point" and it is referenced in our package.json file. By default, the `npm init` command sets this entry file to be `index.js`. After creating the `index.js` file, we will write some code to make our Node app listen to a port for http requests and respond to them — the beginnings of a server.

**Comment by devlemire** [comment]
I like the re-wording, I will update.
