### ISSUE TITLE
RESTful conventions not used

### ISSUE THREAD

**Issue by dallincrane** [DevMountain/DevMtn-Node-Introduction#8]
Although, we may not be introducing RESTful practices on the first day of class or explicitly in this project, we should still be using them to make them naturally familiar. A team using RESTful practices would likely never have a path of `/user-query` or `/user-body`. If we manipulate a collection of objects in this project, it helps the student pick or RESTful practices WAY faster the next day.

Instead of manipulating a single `user` object, create of collection of objects, such as `messages`. For this project the following endpoints would be best (replace messages with whatever):
`GET /messages`
`POST /messages`
`DELETE /messages` <-- clears all the messages

**Comment by devlemire** [comment]
I had the same issue when I was making `/user-query` and `/user-body` ( it felt cheesy ) the reason why I did it this way was to meet the requirement of having to use the `query` and the `body`. An idea comes to mind that I could create one `post` endpoint that will either check for a `req.query` or a `req.body` and use it accordingly. But I wasn't really a 100% on this approach.

The reason why I didn't include a `GET` or `DELETE` was to save time and not deviate from the repository requirements. 

Thoughts?

**Comment by dallincrane** [comment]
My thoughts are that those repository requirements haven't been agreed upon, and in my opinion, should not be changed right now. I was under the impression that this project was just going to replace the current Node Day 1 project, "chatty". This project could either be edited to work with current requirements and _potentially_ updated if/when requirements change OR it needs to be kept on the back burner for if/when the requirements change.

**Comment by jrobber** [comment]
This project will not replace chatty, it will meet the needs of the new curriculum flow, and these requirements make sense in that flow only.  

We include query and body because only 1 day of node is taught that week, and then we teach them how to connect to SQL.   By including query and body at this point we can have more robust and realistic projects for them to work on.

**Comment by dallincrane** [comment]
Then at the very least this teaches students bad practices that will be engrained by use in other project before correcting that practice. Further, we need to address what we are removing from Node Day 1 to have time to consistently teach query params.

**Comment by jrobber** [comment]
We will update the URLs to be a better REST format, there was some confusion from my instructions, but James and I agree with you. We will fix those.

The timing has been talked about and decided on :).

Here is day 1 :
Express
Modules
Static Files
bodyParser
Query
package.json

I feel like it is do-able.
